# Generated by Django 3.0.5 on 2020-06-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='people',
            new_name='Contact',
        ),
    ]
